using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Mono.Material;

[GenerateTypedNameReferences]
public sealed partial class MaterialStorageWindow : FancyWindow
{
    public MaterialStorageWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

