- type: body
  parent: [ PartAnimalBase, BaseTorsoAnimal ]
  id: TorsoAnimal
  name: "animal torso"
  root: torso
  slots:
    head:
      part: HeadAnimal
      connections:
      - torso
      organs:
        brain: OrganAnimalBrain
        eyes: OrganAnimalEyes
    torso:
      part: TorsoAnimal
      organs:
        heart: OrganAnimalHeart
        lungs: OrganAnimalLungs
        stomach: OrganAnimalStomach
        liver: OrganAnimalLiver
        kidneys: OrganAnimalKidneys
      connections:
      - right leg
      - left leg
    right leg:
      part: RightLegAnimal
      connections:
      - right foot
    left leg:
      part: LeftLegAnimal
      connections:
      - left foot
    right foot:
      part: RightFootAnimal
    left foot:
      part: LeftFootAnimal