// SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
// SPDX-FileCopyrightText: 2025 gluesniffler <linebarrelerenthusiast@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Systems.Bwoink;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Shitcode.UserActions.Tabs;

[GenerateTypedNameReferences]
public sealed partial class ConfigTabControl : BaseTabControl
{
    [Dependency] private readonly IClientConsoleHost _console = default!;

    public ConfigTabControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public override bool UpdateState()
    {
        var optionsUIController = UserInterfaceManager.GetUIController<OptionsUIController>();
        var ahelpUIController = UserInterfaceManager.GetUIController<AHelpUIController>();

        MenuList.RemoveAllChildren();

        var disconnectButton = CreateMenuButton(
                "DisconnectButton",
                Loc.GetString("ui-config-menu-disconnect"),
                "/Textures/Interface/VerbIcons/open.svg.192dpi.png");
        disconnectButton.OnPressed += (_) =>
            _console.ExecuteCommand("disconnect");
        MenuList.AddChild(disconnectButton);

        var quitButton = CreateMenuButton(
                "QuitButton",
                Loc.GetString("ui-config-menu-quit"),
                "/Textures/Interface/VerbIcons/Spare/poweronoff.svg.192dpi.png");
        quitButton.OnPressed += (_) =>
            _console.ExecuteCommand("quit");
        MenuList.AddChild(quitButton);

        var optionsButton = CreateMenuButton(
                "OptionsButton",
                Loc.GetString("ui-config-menu-options"),
                "/Textures/Interface/VerbIcons/settings.svg.192dpi.png");
        optionsButton.OnPressed += (_) =>
            optionsUIController.OpenWindow();
        MenuList.AddChild(optionsButton);

        var craftingButton = CreateMenuButton(
                "CraftingButton",
                Loc.GetString("ui-config-menu-crafting"),
                "/Textures/Interface/hammer.svg.192dpi.png");
        craftingButton.OnPressed += (_) =>
            _console.ExecuteCommand("crafting");
        MenuList.AddChild(craftingButton);

        var adminButton = CreateMenuButton(
                "AdminButton",
                Loc.GetString("ui-config-menu-admin"),
                "/Textures/Interface/gavel.svg.192dpi.png");
        adminButton.OnPressed += (_) =>
            _console.ExecuteCommand("admin");
        MenuList.AddChild(adminButton);

        var sandboxButton = CreateMenuButton(
                "SandboxButton",
                Loc.GetString("ui-config-menu-sandbox"),
                "/Textures/Interface/sandbox.svg.192dpi.png");
        sandboxButton.OnPressed += (_) =>
            _console.ExecuteCommand("sandbox");
        MenuList.AddChild(sandboxButton);

        var ahelpButton = CreateMenuButton(
                "AHelpButton",
                Loc.GetString("ui-config-menu-ahelp"),
                "/Textures/Interface/info.svg.192dpi.png");
        ahelpButton.OnPressed += (_) =>
            ahelpUIController.ToggleWindow();
        MenuList.AddChild(ahelpButton);

        UpdateButtonsLayout();
        return true;
    }

    private void UpdateButtonsLayout()
    {
    }

    private Button CreateMenuButton(string controlName, string buttonName, string? texturePath = null)
    {
        return new Button
        {
            Name = controlName,
            Text = buttonName,
            HorizontalExpand = true,
        };
    }

    protected override void Resized()
    {
        UpdateButtonsLayout();
    }
}
