# Separating this for ease of visualization
- type: vessel
  id: BaseVessel
  abstract: true
  # Andromeda start: Localize ship name and desc
  name: vessel-BaseVessel-name
  description: vessel-BaseVessel-desc
  # Andromeda end
  price: 50000
  category: Medium
  group: Shipyard
  addComponents:
  - type: IFF
    color: '#FFFFFFFF'
    flags: [IsPlayerShuttle]

- type: vessel
  id: BaseVesselAntag
  abstract: true
  parent: BaseVessel
  addComponents:
  - type: IFF
    flags: [IsPlayerShuttle, HideLabel]
