- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  #- Amber TODO: goob amber
  - Bagel
  - Box
  - Cluster
  #- Cog # Goobstation - cog is broken
  - Core
  - Fland
  - Gate
  - Loop
  - Marathon
  - Meta
  - Oasis
  - Omega
  #- Origin # Goobstation - its broke
  - Saltern
  - Packed
  - Reach
  #  - Train # Goobstation - all my friends hate train
  - FlandHighPop
  - OasisHighPop
  - Barratry # Goobstation - Re-add barratry
  - Kettle # Goobstation - Re-add kettle (before it was gemini!)
  - Raska # Mono
  - Submarine # goobstation - kill yourse
