- type: job
  id: USMCLieutenant
  name: job-name-usmc-lieutenant
  description: job-description-usmc-lieutenant
  playTimeTracker: JobUSMCLieutenant
  weight: 79
  startingGear: USMCLieutenantGear
  alwaysUseSpawner: true
  icon: "JobIconNATOCaptain"
  requireAdminNotify: true
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    - Esperanto
    languagesUnderstood:
    - English
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  #   components:
  #     # COMMENTED OUT: ChatRank and HullrotFaction not supported
  #     # - type: ChatRank
  #     #   rank: BF-rank-lieutenant
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOCommand
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: USMCLieutenantGear
  equipment:
    id: USMCLieutenantPDA
    ears: ClothingHeadsetAltUS
    belt: ClothingBeltMilitaryWebbingUSFilledSTANAGTracerRed
    jumpsuit: ClothingUniformJumpsuitCamoUS
    head: ClothingHeadHatHelmetUS
    outerClothing: ClothingOuterArmorPlateCarrierTan
    shoes: ClothingShoesBootsJackFilled
    suitstorage: WeaponRifleUSM4A1
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledUSMCRifleman
    rightarmband: ClothingArmbandThighHolsterFilledUS
  storage:
    back:
    - ArmorPlateMedium
    - ClothingMaskGasM40
    - FlashlightMilitaryUS
    - MagazinePistolM9
    - MagazinePistolM9
    - Tourniquet
    - Zipties
