# READ ME
# The purpose of reservist role (whatever title it gets from it's inception) is that it act as a low responsibility role that is overtly part of the faction itself, is non-civilian (that means you are a belligerent and part of the chain of command)
# This role is meant for people who have interests in the relevant faction, compared to a generic spacer or merc siding with TSF/PDV

- type: job
  id: PDVReservist
  name: job-name-pdv-reservist
  description: job-description-pdv-reservist
  playTimeTracker: JobPDVReservist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1000 # Requires you to have atleast logged on the server.
  startingGear: TsfEngiGear
  icon: JobIconPDVReservist
  supervisors: job-supervisors-hire
  weight: 130
  displayWeight: 24
  assignedCompany: PDV
  canBeAntag: false
  access:
  - Pirate
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - PDV
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PDVReservistGear
  equipment:
    head: ClothingHeadHatHardhatOrange
    outerClothing: ClothingOuterVestHazard
    belt: ClothingBeltUtilityEngineering
    suitStorage: MaintenanceJack
  storage:
    back:
    - RadioHandheldNF
    - NFPouchPirate
