- type: startingGear
  id: BF14DeathmatchGear
  equipment:
    head: ClothingHeadHatRichard # miami
    jumpsuit: ClothingUniformJumpsuitTshirtJeans # miami ClothingUniformJumpsuitColorWhite
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesFingerless
    outerClothing: ClothingOuterCoatBomber # miami ClothingOuterArmorWebVestSecEmpty
    shoes: ClothingShoesBootsJackFilled
#miami    back: ClothingBackpackRucksackBlack
    neck: FlashlightMilitaryUS
#miami    suitstorage: WeaponRifleUSM4
#miami    pocket1: WeaponPistolILDeagleSilver
#miami    pocket2: PouchFirstAidFilled
    pocket1: CrowbarMiami
    pocket2: CombatKnife