# Start base CBURN (Rifleman)
- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGear
  icon: "JobIconCBURNSpecialist"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformCcVICT
    back: ClothingBackpackDuffelVICT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesCentComm
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesMopp
    neck: ClothingNeckIFFGreen
    outerClothing: ClothingOuterHardsuitVICT
    shoes: ClothingShoesBootsMagAdv
    id: CBURNPDA
    pocket1: RadioHandheldNF # Frontier: RadioHandheld<RadioHandheldNF
    pocket2: WeaponLaserPistolNF # Frontier: WeaponLaserGun<WeaponLaserPistolNF
    belt: ClothingBeltWebbingsBigRangerGreen
    # suitStorage: PortableRecharger - for some reason it still puts an O2 can here, idrk how to fix it so gg
  inhand:
    - WeaponRifleNtsfLtr # Takes 5.556x45mm or 6.8x52mm
  storage:
    back:
    - GrenadeFlashBang
    - MedkitCombatFilled
    - MedkitCombatFilled
    - ShipVoucherFrontierGuard
    - GrenadeIncendiaryNfsd
    - GrenadeIncendiaryNfsd
    - SyringeCaseAltFilled
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - AmmoBox556x45mmIncendiary
    - AmmoBox556x45mmIncendiary
    - AmmoBox556x45mmPlasteelAP
    - AmmoBox556x45mmIncendiary
    belt:
    - BluespaceLifelineImplanter # Stops stealing of their gear
    - RadioImplanterCentcomm # Headset theft means nothing!
    - HandHeldMassScannerBorg # Just for the infiniste battery
    - TrackingImplanter # TSFMC tracker
    - MedicalTrackingImplanterLabeled # Medical Dispatch Tracker
    - Magazine556x45mmFMJ
    - Magazine556x45mmIncendiary
    - Magazine556x45mmIncendiary
    - Magazine556x45mmIncendiary
    - Magazine556x45mmPlasteelAP
    - Handcuffs
    - Handcuffs

# End base CBURN (Rifleman)

# Start CBURN Leader (FTL)

- type: job
  id: CBURN-LEAD
  name: job-name-cburn-leader
  description: job-description-cburn-leader
  playTimeTracker: JobCBURNFTL
  setPreference: false
  startingGear: CBURNGearLEAD
  icon: "JobIconCBURNLeader"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CBURNGearLEAD
  equipment:
    jumpsuit: ClothingUniformCcVICT
    back: ClothingBackpackDuffelVICT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesCentComm
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesMopp
    neck: ClothingNeckIFFGreen
    outerClothing: ClothingOuterHardsuitVICT
    shoes: ClothingShoesBootsMagAdv
    id: CBURNPDA
    pocket1: RadioHandheldNF # Frontier: RadioHandheld<RadioHandheldNF
    pocket2: WeaponAdvancedLaser
    belt: ClothingBeltWebbingsBigRangerGreen
    # suitStorage: PortableRecharger - for some reason it still puts an O2 can here, idrk how to fix it so gg
  inhand:
    - WeaponRifleNtsfLtr # Takes 5.556x45mm or 6.8x52mm
  storage:
    back:
    - GrenadeFlashBang
    - MedkitCombatFilled
    - MedkitCombatFilled
    - ShipVoucherFrontierGuard
    - GrenadeIncendiaryNfsd
    - GrenadeIncendiaryNfsd
    - SyringeCaseAltFilled
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - AmmoBox556x45mmIncendiary
    - AmmoBox556x45mmIncendiary
    - AmmoBox556x45mmPlasteelAP
    - AmmoBox556x45mmIncendiary
    belt:
    - BluespaceLifelineImplanter # Stops stealing of their gear
    - RadioImplanterCentcomm # Headset theft means nothing!
    - HandHeldMassScannerBorg # Just for the infinite battery
    - TrackingImplanter # TSFMC tracker
    - MedicalTrackingImplanterLabeled # Medical Dispatch Tracker
    - Magazine556x45mmFMJ
    - Magazine556x45mmIncendiary
    - Magazine556x45mmIncendiary
    - Magazine556x45mmIncendiary
    - Magazine556x45mmPlasteelAP
    - Handcuffs
    - Handcuffs
# End CBURN Leader (FTL)

# Start CBURN Medic (VICT-C)

- type: job
  id: CBURN-MEDIC
  name: job-name-cburn-medic
  description: job-description-cburn-medic
  playTimeTracker: JobCBURNMEDIC
  setPreference: false
  startingGear: CBURNGearMedic
  icon: "JobIconCBURNSpecialist"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CBURNGearMedic
  equipment:
    jumpsuit: ClothingUniformCcVICT
    back: ClothingBackpackDuffelVICT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesCentComm
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesMopp
    neck: ClothingNeckIFFGreen
    outerClothing: ClothingOuterHardsuitVICT
    shoes: ClothingShoesBootsMagAdv
    id: CBURNPDA
    pocket1: RadioHandheldNF # Frontier: RadioHandheld<RadioHandheldNF
    pocket2: WeaponAdvancedLaser
    belt: ClothingBeltWebbingsBigRangerGreen
    # suitStorage: PortableRecharger - for some reason it still puts an O2 can here, idrk how to fix it so gg
  inhand:
  - WeaponSubMachineGunVectorNtsfHclm
  storage:
    back:
    - MedkitCombatFilled
    - MedkitCombatFilled
    - MedkitCombatFilled
    - MedkitCombatFilled
    - ShipVoucherFrontierGuard
    - SyringeCaseAltFilled
    - SyringeCaseAltFilled
    - SyringeCaseAltFilled
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - SyringeBluespace
    - SyringeBluespace
    - Jug
    belt:
    - Magazine45_ACPSubMachineGunIncendiary
    - Magazine45_ACPSubMachineGunIncendiary
    - Magazine45_ACPSubMachineGunIncendiary
    - Magazine45_ACPSubMachineGunPlasteelAP
    - Magazine45_ACPSubMachineGunFMJ
    - BluespaceLifelineImplanter # Stops stealing of their gear
    - RadioImplanterCentcomm # Headset theft means nothing!
    - TrackingImplanter # TSFMC tracker
    - MedicalTrackingImplanterLabeled # Medical Dispatch Tracker
    - HandHeldMassScannerBorg # Just for the infiniste battery

# End CBURN Medic (VICT-C)

# Start CBURN Engineer (VICT-TAT)

- type: job
  id: CBURN-TAT
  name: job-name-cburn-engineer
  description: job-description-cburn-engineer
  playTimeTracker: JobCBURNTAT
  setPreference: false
  startingGear: CBURNGearTAT
  icon: "JobIconCBURNSpecialist"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CBURNGearTAT
  equipment:
    jumpsuit: ClothingUniformCcVICT
    back: ClothingBackpackDuffelVICT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesCentComm
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesMopp
    neck: ClothingNeckIFFGreen
    outerClothing: ClothingOuterHardsuitVICT
    shoes: ClothingShoesBootsMagAdv
    id: CBURNPDA
    pocket1: RadioHandheldNF # Frontier: RadioHandheld<RadioHandheldNF
    pocket2: WeaponLaserPistolNF # Frontier: WeaponLaserGun<WeaponLaserPistolNF
    belt: ClothingBeltWebbingsBigRangerGreen
    # suitStorage: PortableRecharger - for some reason it still puts an O2 can here, idrk how to fix it so gg
  inhand:
  - WeaponShotgunEnforcer
  storage:
    back:
    - MedkitCombatFilled
    - ShipVoucherFrontierGuard
    - GrenadeIncendiaryNfsd
    - GrenadeIncendiaryNfsd
    - GrenadeIncendiaryNfsd
    - ExGrenadeNfsd
    - ExGrenadeNfsd
    - NanolaminateFoamGrenade
    - NanolaminateFoamGrenade
    - SyringeCaseAltFilled
    - TrackingImplanter # TSFMC tracker
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - RCDRecharging
    - ShipRepairDeviceRecharging
    belt:
    - AmmoBox12_gaugeIncendiary
    - AmmoBox12_gaugeIncendiary
    - SyndicateJawsOfLife
    - PowerDrill
    - WelderExperimental
    - MedicalTrackingImplanterLabeled # Medical Dispatch Tracker
    - BluespaceLifelineImplanter # Stops stealing of their gear
    - RadioImplanterCentcomm # Headset theft means nothing!
    - HandHeldMassScannerBorg # Just for the infiniste battery

# End CBURN Engineer (VICT-TAT)

# Start CBURN Shotgunner/Breacher (VICT-Point)

- type: job
  id: CBURN-POINT
  name: job-name-cburn-point
  description: job-description-cburn-point
  playTimeTracker: JobCBURNPOINT
  setPreference: false
  startingGear: CBURNGearPOINT
  icon: "JobIconCBURNSpecialist"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: CBURNGearPOINT
  equipment:
    jumpsuit: ClothingUniformCcVICT
    back: ClothingBackpackDuffelVICT
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesCentComm
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesMopp
    neck: ClothingNeckIFFGreen
    outerClothing: ClothingOuterHardsuitVICT
    shoes: ClothingShoesBootsMagAdv
    id: CBURNPDA
    pocket1: RadioHandheldNF # Frontier: RadioHandheld<RadioHandheldNF
    pocket2: HandHeldMassScannerBorg # Just for the infiniste battery
    belt: PortableRecharger
    # suitStorage: PortableRecharger - for some reason it still puts an O2 can here, idrk how to fix it so gg
  inhand:
    - WeaponEnergyShotgun # NT Energy Shotgun
  storage:
    back:
    - WeaponShotgunDoubleBarreled
    - WeaponShotgunHelepolis
    - AmmoBox12_gaugeIncendiary
    - AmmoBox12_gaugeSlug
    - GrenadeFlashBang
    - MedkitCombatFilled
    - ShipVoucherFrontierGuard
    - GrenadeIncendiaryNfsd
    - SyringeCaseAltFilled
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - PillCanisterMesotaxinide # Bottle of 10 15u Mesotaxinide pills
    - Handcuffs
    - TrackingImplanter # TSFMC tracker
    - MedicalTrackingImplanterLabeled # Medical Dispatch Tracker
    - BluespaceLifelineImplanter # Stops stealing of their gear
    - RadioImplanterCentcomm # Headset theft means nothing!
    belt:
    - AmmoBox12_gaugeIncendiary
    - AmmoBox12_gaugeIncendiary

# End CBURN Shotgunner/Breacher (VICT-Point)
