- type: entity
  id: MonoBaseActiveDebris
  abstract: true
  components:
  - type: OwnedDebris
  - type: LocalityLoader
  - type: GCAbleObject
    queue: SpaceDebris
  - type: MapGrid
  - type: IFF
    flags: HideLabel, AlwaysShowColor
  - type: ClaimableGrid # Mono
