- type: accessLevel
  id: Mercenary
  name: id-card-access-level-mercenary

- type: accessLevel
  id: Sergeant
  name: id-card-access-level-sergeant

- type: accessLevel
  id: TSFCaptain
  name: id-card-access-level-tsfcaptain

- type: accessGroup
  id: CadetTsfAccess
  tags:
  - Maintenance
  - External
  - Security
  - Brig

- type: accessGroup
  id: GeneralTsfAccess
  tags:
  - Maintenance
  - External
  - Command
  - Brig
  - Security
  - Mercenary # Frontier
  - Captain # Frontier

- type: accessGroup
  id: GeneralTsfBrigAccess
  tags:
  - Maintenance
  - External
  - Brig

- type: accessGroup
  id: GeneralTsfBrigmedicAccess
  tags:
  - Maintenance
  - External
  - Command
  - Brig
  - Security
  - Mercenary # Frontier
  - Captain # Frontier
  - Chemistry
  - Medical
