- type: job
  id: TSFColonel
  name: job-name-tsf-colonel
  description: job-description-tsf-colonel
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 144000 # 40 hours - mono
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90000 # 25 hours - mono
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 18000 # 5 hours - mono
  whitelisted: true
  startingGear: TSFColonelGear
  alwaysUseSpawner: true
  icon: JobIconTSFColonel
  requireAdminNotify: true
  supervisors: job-supervisors-ws
  weight: 180
  displayWeight: 70
  assignedCompany: TSF
  canBeAntag: false
  accessGroups:
  - AllAccess
  access: # Mono
  - TsfmcEngineering
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon

- type: startingGear
  id: TSFColonelGear
  equipment:
    pocket1: WeaponEnergyGunMultiphase # DeltaV gun
    pocket2: EnergySwordNfsd
  storage:
    back:
    - Multitool
    - DoorRemoteNfsd
    - BaseSecurityUplinkRadioSheriff
    - ShipVoucherTsfmcColonel
    - PhoneInstrumentHigh
