using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.ArtilleryDetection;
using Content.Client.UserInterface.Controls;
using System;
using System.Text;

namespace Content.Client.ArtilleryDetection;

[GenerateTypedNameReferences]
public sealed partial class ArtilleryDetectionConsoleWindow : FancyWindow
{
    public readonly EntityUid Console;

    public Action<Guid>? OnDeleteEvent;
    public Action? OnRefreshRequested;

    private ArtilleryDetectionConsoleState? _currentState;
    private Guid? _selectedEventId;

    public ArtilleryDetectionConsoleWindow(EntityUid console)
    {
        RobustXamlLoader.Load(this);
        Console = console;
        IoCManager.InjectDependencies(this);

        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
        DeleteButton.OnPressed += _ =>
        {
            if (_selectedEventId.HasValue)
                OnDeleteEvent?.Invoke(_selectedEventId.Value);
        };
        ClearAllButton.OnPressed += _ =>
        {
            if (_currentState != null)
            {
                foreach (var evt in _currentState.Events)
                {
                    OnDeleteEvent?.Invoke(evt.Id);
                }
            }
        };

        EventList.OnItemSelected += args =>
        {
            UpdateSelectedEventDetails(args.ItemIndex);
        };

        OnClose += () => Close();
    }

    public void UpdateState(ArtilleryDetectionConsoleState state)
    {
        _currentState = state;
        EventList.Clear();
        ConnectedSystemsList.Clear();

        _selectedEventId = null;
        EventDetailsLabel.Text = "Select an event to view details.";

        foreach (var systemName in state.ConnectedSystems)
        {
            ConnectedSystemsList.AddItem(systemName);
        }

        if (state.Events.Count == 0)
        {
            StatusLabel.Text = "No events detected.";
            return;
        }

        for (int i = 0; i < state.Events.Count; i++)
        {
            var evt = state.Events[i];
            var shortType = !string.IsNullOrEmpty(evt.ArtilleryType) && evt.ArtilleryType != "Unknown"
                ? evt.ArtilleryType
                : evt.WeaponType;
            EventList.AddItem($"[{evt.DetectionTime:mm\\:ss}] {shortType}");
        }

        StatusLabel.Text = $"{state.Events.Count} events detected, {state.ConnectedSystems.Count} systems connected.";
    }

    private void UpdateSelectedEventDetails(int itemIndex)
    {
        if (_currentState == null || itemIndex < 0 || itemIndex >= _currentState.Events.Count)
        {
            _selectedEventId = null;
            EventDetailsLabel.Text = "Select an event to view details.";
            return;
        }

        var evt = _currentState.Events[itemIndex];
        _selectedEventId = evt.Id;

        var detailsBuilder = new StringBuilder();
        detailsBuilder.Append($"Time: {evt.DetectionTime:mm\\:ss}");
        detailsBuilder.Append('\n');
        detailsBuilder.Append($"Weapon: {evt.WeaponType}");
        detailsBuilder.Append('\n');
        detailsBuilder.Append($"Coordinates: ({evt.DetectedCoordinates.X:F1}, {evt.DetectedCoordinates.Y:F1})");
        detailsBuilder.Append('\n');

        if (!string.IsNullOrEmpty(evt.ArtilleryType) && evt.ArtilleryType != "Unknown")
        {
            detailsBuilder.Append($"Artillery: {evt.ArtilleryType}");
            detailsBuilder.Append('\n');
        }

        if (!string.IsNullOrEmpty(evt.ProjectileType) && evt.ProjectileType != "Unknown")
        {
            detailsBuilder.Append($"Projectile: {evt.ProjectileType}");
            detailsBuilder.Append('\n');
        }

        detailsBuilder.Append($"Event ID: {evt.LocalId}");
        EventDetailsLabel.Text = detailsBuilder.ToString();
    }
}
