name: PR Changelogs
concurrency: commit_action-${{ github.event.pull_request.base.ref }} # Mono
on:
  pull_request_target:
    types: [closed]

env:
  CHANGELOG_DIR: Resources/Changelog/Monolith.yml # Mono
  PR_NUMBER: ${{ github.event.number }}
  CHANGELOG_USER: "OrehumChangelog[bot]"
  CHANGELOG_EMAIL: "OrehumChangelog[bot]@://github.com"
  CHANGELOG_MESSAGE: "Automatic changelog update"

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          
      - name: Checkout Base Branch # Mono
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: "${{ github.event.pull_request.base.ref }}" # Mono

      - name: Setup Git
        run: |
          git config --global user.name "${{ env.CHANGELOG_USER }}"
          git config --global user.email "${{ env.CHANGELOG_EMAIL }}"
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd "Tools/changelog"
          npm install
        shell: bash

      - name: Generate Changelog
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          CHANGELOG_DIR: ${{ env.CHANGELOG_DIR }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ env.PR_NUMBER }}
        run: |
          cd "Tools/changelog"
          node changelog.js
        shell: bash

      - name: Commit Changelog
        run: |
          git pull origin "${{ github.event.pull_request.base.ref }}"
          git add "${{ env.CHANGELOG_DIR }}"
          git commit -m "Automated Changelog (#${{ env.PR_NUMBER }})"
          git push origin "${{ github.event.pull_request.base.ref }}"
        shell: bash
        continue-on-error: true
